export const productos = [
  { id: 1, nombre: "Cuaderno Universitario 100 hojas", precio: 15.99, stock: 50, imagen: "https://production-tailoy-repo-magento-statics.s3.amazonaws.com/imagenes/872x872/productos/i/c/u/cuad-dlx-80h-cdmax-sol-chiki-colleg-cele-66730004-default-1.jpg", enlace: "cuaderno-universitario" },
  { id: 2, nombre: "Lapiceros Azules (Pack de 12)", precio: 9.99, stock: 100, imagen: "https://production-tailoy-repo-magento-statics.s3.amazonaws.com/imagenes/872x872/productos/i/c/u/cuad-dlx-80h-cdmax-sol-chiki-colleg-cele-66730004-default-1.jpg", enlace: "lapiceros-azules" },
  { id: 3, nombre: "Mochila Escolar Resistente", precio: 89.99, stock: 20, imagen: "https://production-tailoy-repo-magento-statics.s3.amazonaws.com/imagenes/872x872/productos/i/c/u/cuad-dlx-80h-cdmax-sol-chiki-colleg-cele-66730004-default-1.jpg", enlace: "mochila-escolar" },
  { id: 4, nombre: "Colores de Madera (Caja de 24)", precio: 25.50, stock: 40, imagen: "https://production-tailoy-repo-magento-statics.s3.amazonaws.com/imagenes/872x872/productos/i/c/u/cuad-dlx-80h-cdmax-sol-chiki-colleg-cele-66730004-default-1.jpg", enlace: "colores-madera" },
  { id: 5, nombre: "Regla de 30 cm Transparente", precio: 5.99, stock: 80, imagen: "https://production-tailoy-repo-magento-statics.s3.amazonaws.com/imagenes/872x872/productos/i/c/u/cuad-dlx-80h-cdmax-sol-chiki-colleg-cele-66730004-default-1.jpg", enlace: "regla-30cm" },
  { id: 6, nombre: "Borradores Blancos (Pack de 3)", precio: 4.99, stock: 60, imagen: "https://production-tailoy-repo-magento-statics.s3.amazonaws.com/imagenes/872x872/productos/i/c/u/cuad-dlx-80h-cdmax-sol-chiki-colleg-cele-66730004-default-1.jpg", enlace: "borradores-blancos" },
  { id: 7, nombre: "Sacapuntas Metálico", precio: 3.99, stock: 70, imagen: "https://production-tailoy-repo-magento-statics.s3.amazonaws.com/imagenes/872x872/productos/i/c/u/cuad-dlx-80h-cdmax-sol-chiki-colleg-cele-66730004-default-1.jpg", enlace: "sacapuntas-metalico" },
  { id: 8, nombre: "Calculadora Científica", precio: 119.99, stock: 15, imagen: "https://production-tailoy-repo-magento-statics.s3.amazonaws.com/imagenes/872x872/productos/i/c/u/cuad-dlx-80h-cdmax-sol-chiki-colleg-cele-66730004-default-1.jpg", enlace: "calculadora-cientifica" },
  { id: 9, nombre: "Resaltadores Fluorescentes (Pack de 5)", precio: 18.99, stock: 35, imagen: "https://production-tailoy-repo-magento-statics.s3.amazonaws.com/imagenes/872x872/productos/i/c/u/cuad-dlx-80h-cdmax-sol-chiki-colleg-cele-66730004-default-1.jpg", enlace: "resaltadores-fluorescentes" },
  { id: 10, nombre: "Compás Metálico con Estuche", precio: 22.99, stock: 25, imagen: "https://production-tailoy-repo-magento-statics.s3.amazonaws.com/imagenes/872x872/productos/i/c/u/cuad-dlx-80h-cdmax-sol-chiki-colleg-cele-66730004-default-1.jpg", enlace: "compas-metalico" },
  { id: 11, nombre: "Tijeras Escolares Punta Redonda", precio: 7.99, stock: 45, imagen: "https://production-tailoy-repo-magento-statics.s3.amazonaws.com/imagenes/872x872/productos/i/c/u/cuad-dlx-80h-cdmax-sol-chiki-colleg-cele-66730004-default-1.jpg", enlace: "tijeras-escolares" },
  { id: 12, nombre: "Cartuchera Grande con Compartimentos", precio: 39.99, stock: 30, imagen: "https://production-tailoy-repo-magento-statics.s3.amazonaws.com/imagenes/872x872/productos/i/c/u/cuad-dlx-80h-cdmax-sol-chiki-colleg-cele-66730004-default-1.jpg", enlace: "cartuchera-grande" },
  { id: 13, nombre: "Pegamento en Barra 20g", precio: 6.50, stock: 55, imagen: "https://production-tailoy-repo-magento-statics.s3.amazonaws.com/imagenes/872x872/productos/i/c/u/cuad-dlx-80h-cdmax-sol-chiki-colleg-cele-66730004-default-1.jpg", enlace: "pegamento-barra" },
  { id: 14, nombre: "Set de Geometría (Escuadra, Transportador, Regla)", precio: 14.99, stock: 20, imagen: "https://production-tailoy-repo-magento-statics.s3.amazonaws.com/imagenes/872x872/productos/i/c/u/cuad-dlx-80h-cdmax-sol-chiki-colleg-cele-66730004-default-1.jpg", enlace: "set-geometria" },
  { id: 15, nombre: "Forro de Libros Adhesivo Transparente", precio: 12.99, stock: 40, imagen: "https://production-tailoy-repo-magento-statics.s3.amazonaws.com/imagenes/872x872/productos/i/c/u/cuad-dlx-80h-cdmax-sol-chiki-colleg-cele-66730004-default-1.jpg", enlace: "forro-libros" }
];
